"""
Methods for generating Structured Text using PLCOpen editor.

Authors

- Christopher Goes

This docstring has a high level overview of the logic extraction and generation process.
More information can be obtained on the PEAT Wiki, or by emailing the author.

The PLCOpen editor is a open-source (GPLv3) graphical tool for working with PLC logic,
similar to Schneider's Unity or RockWell's Studio 5000.

PEAT uses the editor's logic generation components to convert a
TC6 XML project file into IEC 61131-3 compliant Structured Text (ST).
PEAT provides functions to generate the structure and elements of the TC6 XML file.
Individual modules generate logic by utilizing these functions to convert from the device's
proprietary format to a valid TC6 XML project file that can then be converted to ST.

"TC6 XML" is a PLCOpen group specification defining a portable structure
for tools working with IEC 61131-3 languages.

IEC 61131-3 is the standard defining the 5 PLC programming languages:

- Structured Text (ST)
- Ladder Logic (LD)
- Function-Block Diagram (FBD)
- Instruction List (IL)
- Sequential Function Chart (SFC)
"""


from peat import log

from .plc_open import PLCControler


def tc6_to_st(tc6_xml: bytes, output_filepath: str | None = None) -> str:
    """
    Converts TC6 XML into IEC 61131-3 compliant Structured Text.

    How to use in your module:

    - Create a file using utils.generate_filepath
    - Write the spec to the file (in "w" mode)
    - Provide the absolute filepath to this function

    .. warning::
       This is the function that calls into the PLCOpen codebase,
       and therefore will be the source of errors relating to PLCOpen.

    Args:
        tc6_xml: Encoded TC6 XML byte string to be parsed by PLCOpen
        output_filepath: Path to save the ST program to, in addition to the return

    Returns:
        The Structured Text program as UTF8 text
    """
    log.debug("Converting TC6 XML to Structured Text...")
    if not tc6_xml:
        log.error("Failed to parse TC6 XML: the passed tc6_xml string is empty")
        return ""

    # Instantiate the controller object used to manage state and generate the program
    # Yes, that is misspelled. PLCOpen Editor devs are non-native English speakers.
    controller = PLCControler()

    # Read the TC6-formatted XML file into the PLCController instance
    error = controller.load_project(tc6_xml)
    if error and "tc6_0201}body" in str(error):
        log.warning(
            "PLCOpen parsing failed because there's "
            "no structured text in the TC6 XML"
        )
        return ""
    elif error:
        log.error(f"PLCOpen error parsing the TC6 XML: {error}")
        return ""

    # Generate the ST program from the state of the PLCController instance
    program, errors, warnings = controller.GenerateProgram(output_filepath)

    # Warnings and errors generated by PLCOpen during the generation process
    for i, error in enumerate(errors):
        log.error(f"PLCOpen error {i}: {error}")
    for i, warning in enumerate(warnings):
        log.warning(f"PLCOpen warning {i}: {warning}")

    log.debug("Finished converting TC6 XML file to Structured Text")
    return str(program)  # convert bytes to string
