# PySNMP SMI module. Autogenerated from smidump -f python SipGoose
# by libsmi2pysnmp-0.1.3
# Python version sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( siprotec, ) = mibBuilder.importSymbols("SIEMENS-SMI", "siprotec")
( Bits, Integer32, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Integer32", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks")

# Objects

goose = ModuleIdentity((1, 3, 6, 1, 4, 1, 22638, 1, 2)).setRevisions(("2004-11-23 09:13",))
if mibBuilder.loadTexts: goose.setOrganization("Organization ")
if mibBuilder.loadTexts: goose.setContactInfo("Contact-info")
if mibBuilder.loadTexts: goose.setDescription("Description")
nRxMatchedTel = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 2, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: nRxMatchedTel.setDescription("Number of matched telegrams for GOOSE received.")
nRxMismatchTel = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 2, 2), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: nRxMismatchTel.setDescription("Number of mismatched telegram for GOOSE received.")

# Augmentions

# Exports

# Module identity
mibBuilder.exportSymbols("SipGoose", PYSNMP_MODULE_ID=goose)

# Objects
mibBuilder.exportSymbols("SipGoose", goose=goose, nRxMatchedTel=nRxMatchedTel, nRxMismatchTel=nRxMismatchTel)

