# PySNMP SMI module. Autogenerated from smidump -f python SipOptical
# by libsmi2pysnmp-0.1.3
# Python version sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)

# Imports

( Integer, ObjectIdentifier, OctetString, ) = mibBuilder.importSymbols("ASN1", "Integer", "ObjectIdentifier", "OctetString")
( NamedValues, ) = mibBuilder.importSymbols("ASN1-ENUMERATION", "NamedValues")
( ConstraintsIntersection, ConstraintsUnion, SingleValueConstraint, ValueRangeConstraint, ValueSizeConstraint, ) = mibBuilder.importSymbols("ASN1-REFINEMENT", "ConstraintsIntersection", "ConstraintsUnion", "SingleValueConstraint", "ValueRangeConstraint", "ValueSizeConstraint")
( siprotec, ) = mibBuilder.importSymbols("SIEMENS-SMI", "siprotec")
( ObjectGroup, ) = mibBuilder.importSymbols("SNMPv2-CONF", "ObjectGroup")
( Bits, Counter32, Integer32, Integer32, ModuleIdentity, MibIdentifier, MibScalar, MibTable, MibTableRow, MibTableColumn, TimeTicks, Unsigned32, ) = mibBuilder.importSymbols("SNMPv2-SMI", "Bits", "Counter32", "Integer32", "Integer32", "ModuleIdentity", "MibIdentifier", "MibScalar", "MibTable", "MibTableRow", "MibTableColumn", "TimeTicks", "Unsigned32")

# Objects

opticalMIB = ModuleIdentity((1, 3, 6, 1, 4, 1, 22638, 1, 3)).setRevisions(("2004-11-23 09:13",))
if mibBuilder.loadTexts: opticalMIB.setOrganization("Organization")
if mibBuilder.loadTexts: opticalMIB.setContactInfo("Contact-info")
if mibBuilder.loadTexts: opticalMIB.setDescription("Description")
structureId = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 1), Counter32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: structureId.setDescription("identification of the structure in the optical module")
opMode = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 2), Integer().subtype(subtypeSpec=SingleValueConstraint(1,2,)).subtype(namedValues=NamedValues(("line", 1), ("switch", 2), ))).setMaxAccess("readonly")
if mibBuilder.loadTexts: opMode.setDescription("mode of operation")
rstp = MibIdentifier((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4))
bridgePrior = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 1), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: bridgePrior.setDescription("bridge priority")
bridgeId = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 2), Integer32().clone(2048)).setMaxAccess("readonly")
if mibBuilder.loadTexts: bridgeId.setDescription("RSTP specific parameter")
helloTimer = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 3), Integer32().subtype(subtypeSpec=ValueRangeConstraint(1, 10)).clone(2)).setMaxAccess("readonly")
if mibBuilder.loadTexts: helloTimer.setDescription("RSTP specific parameter value of times is in sec")
maxAgeTime = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 4), Integer32().subtype(subtypeSpec=ValueRangeConstraint(6, 40)).clone(20)).setMaxAccess("readonly")
if mibBuilder.loadTexts: maxAgeTime.setDescription("RSTP specific parameter. value is in seconds")
forwardDelay = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 5), Integer32().subtype(subtypeSpec=ValueRangeConstraint(4, 30)).clone(15)).setMaxAccess("readonly")
if mibBuilder.loadTexts: forwardDelay.setDescription("RSTP specific parameter")
priority = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 6), Integer32().clone(128)).setMaxAccess("readonly")
if mibBuilder.loadTexts: priority.setDescription("RSTP specific parameter")
maxTransmitCount = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 7), Integer32().subtype(subtypeSpec=ValueRangeConstraint(3, 128)).clone(10)).setMaxAccess("readonly")
if mibBuilder.loadTexts: maxTransmitCount.setDescription("RSTP specific parameter")
rstpCost = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 8), Integer32().clone(200000)).setMaxAccess("readonly")
if mibBuilder.loadTexts: rstpCost.setDescription("RSTP specific parameter. value of -1 is for automatic mode")
rstpNeighbourPortA = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 9), OctetString().subtype(subtypeSpec=ValueSizeConstraint(6, 6)).setFixedLength(6)).setMaxAccess("readonly")
if mibBuilder.loadTexts: rstpNeighbourPortA.setDescription("MAC address from neighbour on EN100 port A.")
rstpNeighbourPortB = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 10), OctetString().subtype(subtypeSpec=ValueSizeConstraint(6, 6)).setFixedLength(6)).setMaxAccess("readonly")
if mibBuilder.loadTexts: rstpNeighbourPortB.setDescription("MAC address from neighbour on EN100 port B.")
epldVersion = MibScalar((1, 3, 6, 1, 4, 1, 22638, 1, 3, 4, 11), Integer32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: epldVersion.setDescription("EPLD-Version")
opticalTransceiverTable = MibTable((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5))
if mibBuilder.loadTexts: opticalTransceiverTable.setDescription("")
opticalTransceiverEntry = MibTableRow((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1)).setIndexNames((0, "SipOptical", "channel"))
if mibBuilder.loadTexts: opticalTransceiverEntry.setDescription("")
channel = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 1), Integer32().subtype(subtypeSpec=ValueRangeConstraint(0, 1))).setMaxAccess("readonly")
if mibBuilder.loadTexts: channel.setDescription("")
txPacket = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 2), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: txPacket.setDescription("")
rxPacket = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 3), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: rxPacket.setDescription("")
filterSrc = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 4), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: filterSrc.setDescription("")
filterDest = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 5), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: filterDest.setDescription("")
filterCrcErrCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 6), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: filterCrcErrCnt.setDescription("")
filterLenErrCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 7), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: filterLenErrCnt.setDescription("")
filterSymErrCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 8), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: filterSymErrCnt.setDescription("")
overflowExtCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 9), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: overflowExtCnt.setDescription("")
overflowIntCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 10), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: overflowIntCnt.setDescription("")
overflowIntTraCnt = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 11), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: overflowIntTraCnt.setDescription("")
optLevel = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 12), Unsigned32()).setMaxAccess("readonly")
if mibBuilder.loadTexts: optLevel.setDescription("")
vendor = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 13), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 16))).setMaxAccess("readonly")
if mibBuilder.loadTexts: vendor.setDescription("")
partNo = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 14), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 16))).setMaxAccess("readonly")
if mibBuilder.loadTexts: partNo.setDescription("")
revision = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 15), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 4))).setMaxAccess("readonly")
if mibBuilder.loadTexts: revision.setDescription("")
temperature = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 16), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 10))).setMaxAccess("readonly")
if mibBuilder.loadTexts: temperature.setDescription("")
powerSupply = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 17), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 10))).setMaxAccess("readonly")
if mibBuilder.loadTexts: powerSupply.setDescription("")
txBias = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 18), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 10))).setMaxAccess("readonly")
if mibBuilder.loadTexts: txBias.setDescription("")
txPower = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 19), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 10))).setMaxAccess("readonly")
if mibBuilder.loadTexts: txPower.setDescription("")
rxPower = MibTableColumn((1, 3, 6, 1, 4, 1, 22638, 1, 3, 5, 1, 20), OctetString().subtype(subtypeSpec=ValueSizeConstraint(0, 10))).setMaxAccess("readonly")
if mibBuilder.loadTexts: rxPower.setDescription("")
groups = MibIdentifier((1, 3, 6, 1, 4, 1, 22638, 1, 3, 7))

# Augmentions

# Groups

opticalGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 22638, 1, 3, 7, 1)).setObjects(*(("SipOptical", "redundancyAlgo"), ("SipOptical", "structureId"), ("SipOptical", "opMode"), ) )
if mibBuilder.loadTexts: opticalGroup.setDescription("A collection of Optical objects.")
rstpGroup = ObjectGroup((1, 3, 6, 1, 4, 1, 22638, 1, 3, 7, 2)).setObjects(*(("SipOptical", "maxAgeTime"), ("SipOptical", "rstpNeighbourPortB"), ("SipOptical", "rstpNeighbourPortA"), ("SipOptical", "helloTimer"), ("SipOptical", "maxTransmitCount"), ("SipOptical", "bridgePrior"), ("SipOptical", "rstpCost"), ("SipOptical", "forwardDelay"), ("SipOptical", "priority"), ("SipOptical", "epldVersion"), ("SipOptical", "bridgeId"), ) )
if mibBuilder.loadTexts: rstpGroup.setDescription("A collection of Optical objects.")
opticalChannel = ObjectGroup((1, 3, 6, 1, 4, 1, 22638, 1, 3, 7, 3)).setObjects(*(("SipOptical", "filterSymErrCnt"), ("SipOptical", "vendor"), ("SipOptical", "temperature"), ("SipOptical", "filterLenErrCnt"), ("SipOptical", "filterSrc"), ("SipOptical", "txPower"), ("SipOptical", "txBias"), ("SipOptical", "rxPower"), ("SipOptical", "powerSupply"), ("SipOptical", "rxPacket"), ("SipOptical", "partNo"), ("SipOptical", "overflowIntTraCnt"), ("SipOptical", "overflowIntCnt"), ("SipOptical", "optLevel"), ("SipOptical", "txPacket"), ("SipOptical", "filterCrcErrCnt"), ("SipOptical", "overflowExtCnt"), ("SipOptical", "filterDest"), ("SipOptical", "channel"), ("SipOptical", "revision"), ) )
if mibBuilder.loadTexts: opticalChannel.setDescription("")

# Exports

# Module identity
mibBuilder.exportSymbols("SipOptical", PYSNMP_MODULE_ID=opticalMIB)

# Objects
mibBuilder.exportSymbols("SipOptical", opticalMIB=opticalMIB, structureId=structureId, opMode=opMode, rstp=rstp, bridgePrior=bridgePrior, bridgeId=bridgeId, helloTimer=helloTimer, maxAgeTime=maxAgeTime, forwardDelay=forwardDelay, priority=priority, maxTransmitCount=maxTransmitCount, rstpCost=rstpCost, rstpNeighbourPortA=rstpNeighbourPortA, rstpNeighbourPortB=rstpNeighbourPortB, epldVersion=epldVersion, opticalTransceiverTable=opticalTransceiverTable, opticalTransceiverEntry=opticalTransceiverEntry, channel=channel, txPacket=txPacket, rxPacket=rxPacket, filterSrc=filterSrc, filterDest=filterDest, filterCrcErrCnt=filterCrcErrCnt, filterLenErrCnt=filterLenErrCnt, filterSymErrCnt=filterSymErrCnt, overflowExtCnt=overflowExtCnt, overflowIntCnt=overflowIntCnt, overflowIntTraCnt=overflowIntTraCnt, optLevel=optLevel, vendor=vendor, partNo=partNo, revision=revision, temperature=temperature, powerSupply=powerSupply, txBias=txBias, txPower=txPower, rxPower=rxPower, groups=groups)

# Groups
mibBuilder.exportSymbols("SipOptical", opticalGroup=opticalGroup, rstpGroup=rstpGroup, opticalChannel=opticalChannel)

