CLOSE_LOGIC_KEYS = [
    "CLS",
    "ULCLS",
    "CLT",
    "ULCLT",
    "CLU",
    "ULCLU",
    "CLW",
    "ULCLW",
    "CLX",
    "ULCLX",
    "CFD",
    "52A",
    "52AA",
    "52AB",
    "52AC",
    "CL",
    "ULCL",
    "79RI",
    "79RIS",
    "79DTL",
    "79DLS",
    "79SKP",
    "79STL",
    "79BRS",
    "79SEQ",
    "79CLS",
    "52A1",
    "52A2",
    "52A3",
    "52A4",
    "CL1",
    "CL2",
    "CL3",
    "CL4",
    "ULCL1",
    "ULCL2",
    "ULCL3",
    "ULCL4",
    "CFDX",
    "CLX",
    "CFDY",
    "CLY",
    "ULCLY",
]  # type: list[str]

OUTPUT_LOGIC_KEYS = [
    "OUT101",
    "OUT102",
    "OUT103",
    "OUT104",
    "OUT105",
    "OUT106",
    "OUT107",
    "OUT201",
    "OUT202",
    "OUT203",
    "OUT204",
    "OUT205",
    "OUT206",
    "OUT301",
    "OUT302",
    "OUT303",
    "OUT304",
    "OUT305",
    "OUT306",
    "OUT307",
    "OUT308",
    "OUT309",
    "OUT309",
    "OUT310",
    "OUT311",
    "OUT312",
    "OUT313",
    "OUT314",
    "OUT315",
    "OUT316",
]  # type: list[str]

TRIP_LOGIC_KEYS = [
    "TR",
    "TR1",
    "TR2",
    "TR3",
    "TR4",
    "TR5",
    "ULTR",
    "ULTR1",
    "ULTR2",
    "ULTR2",
    "ULTR3",
    "ULTR4",
    "ULTR5",
    "TRCOMM",
    "TRSOTF",
    "DTT",
    "E3PT",
    "TRQUAL",
    "ULMTR1",
    "ULMTR2",
    "BK1MTR",
    "BK2MTR",
    "MTU1",
    "MTU2",
    "MTU3",
    "MER",
    "OUT1",
    "OUT2",
    "OUT3",
    "OUT4",
    "TRXFMR",
    "ULTXFMR",
    "TRS",
    "ULTRS",
    "TRT",
    "ULTRT",
    "TRU",
    "ULTRU",
    "TRW",
    "ULTRW",
    "TRX",
    "ULTRX",
    "TDURD",
    "ER",
    "FAULT",
    "REMTRIP",
    "ULTR1",
    "ULTR2",
    "ULTR3",
    "ULTRIP",
]  # type: list[str]

LOGIC_KEYS = {
    "CLOSE_LOGIC": CLOSE_LOGIC_KEYS,
    "OUTPUT_LOGIC": OUTPUT_LOGIC_KEYS,
    "TRIP_LOGIC": TRIP_LOGIC_KEYS,
}  # type: dict[str, list[str]]


# Parse relay protection schemes
ANSI_CODES = {
    "1": "Master Element",
    "2": "Time-delay Starting or Closing Relay",
    "3": "Checking or Interlocking Relay",
    "4": "Master Contactor",
    "5": "Stopping Device",
    "6": "Starting Circuit Breaker",
    "7": "Rate of Change Relay",
    "8": "Control Power Disconnecting Device",
    "9": "Reversing Device",
    "10": "Unit Sequence Switch",
    "11": "Multifunction Device",
    "12": "Overspeed Device",
    "13": "Synchronous:Speed Device",
    "14": "Underspeed Device",
    "15": "Speed or Frequency Matching Device",
    "16": "Data Communications Device",
    "17": "Shunting or Discharge Switch",
    "18": "Accelerating or Decelerating Device",
    "19": "Starting-to-Running Transition Contactor",
    "20": "Electrically-Operated Valve",
    "21": "Distance Relay",
    "21G": "Ground Distance",
    "21P": "Phase Distance",
    "22": "Equalizer circuit breaker",
    "23": "Temperature control device",
    "24": "Volts per hertz relay",
    "25": "Synchronizing or synchronism-check device",
    "26": "Apparatus thermal device",
    "27": "Undervoltage relay",
    "27P": "Phase Undervoltage",
    "27S": "DC undervoltage relay",
    "27TN": "Third Harmonic Neutral Undervoltage",
    "27TN/59N": "100% Stator Earth Fault",
    "27X": "Auxiliary Undervoltage",
    "27AUX": "Undervoltage Auxiliary Input",
    "27X": "Line Undervoltage",  # noqa: F601
    "27/50": "Accidental Generator Energization",
    "28": "Flame Detector",
    "29": "Isolating Contactor",
    "30": "Annunciator Relay",
    "31": "Separate Excitation Device",
    "32": "Directional Power Relay",
    "32L": "Low Forward Power",
    "32N": "Wattmetric Zero:Sequence Directional",
    "32P": "Directional Power",
    "32R": "Reverse Power",
    "33": "Position Switch",
    "34": "Master Sequence Device",
    "35": "Brush-Operating or Slip-ring Short Circuiting Device",
    "36": "Polarity or Polarizing Voltage Device",
    "37": "Undercurrent or Underpower Relay",
    "37P": "Underpower",
    "38": "Bearing Protective Device / Bearing Rtd",
    "39": "Mechanical Condition Monitor",
    "40": "Field Relay / Loss of Excitation",
    "41": "Field Circuit Breaker",
    "42": "Running Circuit Breaker",
    "43": "Manual Transfer or Selector Device",
    "44": "Unit Sequence Starting Relay",
    "45": "Atmospheric Condition Monitor",
    "46": "Reverse-Phase or Phase Balance Current Relay or Stator Current Unbalance",
    "47": "Phase-Sequence or Phase Balance Voltage Relay",
    "48": "Incomplete Sequence Relay / Blocked Rotor",
    "49": "Machine or Transformer Thermal Relay / Thermal Overload",
    "49RTD": "RTD Biased Thermal Overload",
    "50": "Instantaneous Overcurrent Relay",
    "50BF": "Breaker Failure",
    "50DD": "Current Disturbance Detector",
    "50EF": "End Fault Protection",
    "50G": "Ground Instantaneous Overcurrent",
    "50IG": "Isolated Ground Instantaneous Overcurrent",
    "50LR": "Acceleration Time",
    "50N": "Neutral Instantaneous Overcurrent",
    "50NBF": "Neutral Instantaneous Breaker Failure",
    "50P": "Phase Instantaneous Overcurrent",
    "50SG": "Sensitive Ground Instantaneous Overcurrent",
    "50SP": "Split Phase Instantaneous Current",
    "50Q": "Negative Sequence Instantaneous Overcurrent",
    "50/27": "Accidental Energization",
    "50/51": "Instantaneous / Time-delay Overcurrent relay",
    "50Ns/51Ns": "Sensitive earth-fault protection",
    "50/74": "Ct Trouble",
    "50/87": "Instantaneous Differential",
    "51": "AC Time Overcurrent Relay",
    "51": "Overload",  # noqa: F601
    "51G": "Ground Time Overcurrent",
    "51LR": "AC inverse time overcurrent (locked rotor) protection relay",
    "51N": "Neutral Time Overcurrent",
    "51P": "Phase Time Overcurrent",
    "51R": "Locked / Stalled Rotor",
    "51V": "Voltage Restrained Time Overcurrent",
    "51Q": "Negative Sequence Time Overcurrent",
    "52": "AC circuit breaker",
    "52a": "AC circuit breaker position (contact open when circuit breaker open)",
    "52b": "AC circuit breaker position (contact closed when circuit breaker open)",
    "53": "Exciter or Dc Generator Relay",
    "54": "Turning Gear Engaging Device",
    "55": "Power Factor Relay",
    "56": "Field Application Relay",
    "57": "Short-Circuiting or Grounding Device",
    "58": "Rectification Failure Relay",
    "59": "Overvoltage Relay",
    "59B": "Bank Phase Overvoltage",
    "59P": "Phase Overvoltage",
    "59N": "Neutral Overvoltage",
    "59NU": "Neutral Voltage Unbalance",
    "59P": "Phase Overvoltage",  # noqa: F601
    "59X": "Auxiliary Overvoltage",
    "59Q": "Negative Sequence Overvoltage",
    "60": "Voltage or Current Balance Relay",
    "60N": "Neutral Current Unbalance",
    "60P": "Phase Current Unbalance",
    "61": "Density Switch or Sensor",
    "62": "Time-Delay Stopping or Opening Relay",
    "63": "Pressure Switch Detector",
    "64": "Ground Protective Relay",
    "64F": "Field Ground Protection",
    "64R": "Rotor earth fault",
    "64REF": "Restricted earth fault differential",
    "64S": "Stator earth fault",
    "64TN": "100% Stator Ground",
    "65": "Governor",
    "66": "Notching or Jogging Device/Maximum Starting Rate/Starts Per Hour/Time Between Starts",
    "67": "AC Directional Overcurrent Relay",
    "67G": "Ground Directional Overcurrent",
    "67N": "Neutral Directional Overcurrent",
    "67Ns": "Earth fault directional",
    "67P": "Phase Directional Overcurrent",
    "67SG": "Sensitive Ground Directional Overcurrent",
    "67Q": "Negative Sequence Directional Overcurrent",
    "68": "Blocking Relay / Power Swing Blocking",
    "69": "Permissive Control Device",
    "70": "Rheostat",
    "71": "Liquid Switch",
    "72": "DC Circuit Breaker",
    "73": "Load-Resistor Contactor",
    "74": "Alarm Relay",
    "75": "Position Changing Mechanism",
    "76": "DC Overcurrent Relay",
    "77": "Telemetering Device",
    "78": "Phase Angle Measuring or Out-of-Step Protective Relay",
    "78V": "Loss of Mains",
    "79": "AC Reclosing Relay / Auto Reclose",
    "80": "Liquid or Gas Flow Relay",
    "81": "Frequency Relay",
    "81O": "Over Frequency",
    "81R": "Rate-of-Change Frequency",
    "81U": "Under Frequency",
    "82": "DC Reclosing Relay",
    "83": "Automatic Selective Control or Transfer Relay",
    "84": "Operating Mechanism",
    "85": "Pilot Communications, Carrier or Pilot:Wire Relay",
    "86": "Lock-Out Relay, Master Trip Relay",
    "87": "Differential Protective Relay",
    "87B": "Bus Differential",
    "87G": "Generator Differential",
    "87GT": "Generator/Transformer Differential",
    "87L": "Segregated Line Current Differential",
    "87LG": "Ground Line Current Differential",
    "87M": "Motor Differential",
    "87O": "Overall Differential",
    "87PC": "Phase Comparison",
    "87RGF": "Restricted Ground Fault",
    "87S": "Stator Differential",
    "87S": "Percent Differential",  # noqa: F601
    "87T": "Transformer Differential",
    "87V": "Voltage Differential",
    "88": "Auxiliary Motor or Motor Generator",
    "89": "Line Switch",
    "90": "Regulating Device",
    "91": "Voltage Directional Relay",
    "92": "Voltage And Power Directional Relay",
    "93": "Field-Changing Contactor",
    "94": "Tripping or Trip-Free Relay",
}  # type: dict[str, str]


# ---------------------- RTAC ----------------------

RTAC_DB_NAME = "3530"

# Hard coded definition of tables to expect in RTAC PostgreSQL database.
RTAC_DB_TABLES = {
    "device_info": "public",
    "permission_membership": "public",
    "projects": "public",
    "remote_devices": "public",
    "role_master": "public",
    "role_membership": "public",
    "role_permissions": "public",
    "root_devices": "public",
    "round_robin_schema_states": "public",
    "round_robin_schemas": "public",
    "schemas": "public",
    "sel_info": "public",
    "system_permissions": "public",
    "system_role_resource_assoc": "public",
    "system_roles": "public",
    "user_lockouts": "public",
    "user_membership": "public",
    "user_passwords": "public",
    "user_resources": "public",
    "user_roles": "public",
    "user_web_settings": "public",
    "users": "public",
    "users_transient_history": "public",
    "access_point_ethernet_settings": "schema_fw",
    "access_point_routers": "schema_fw",
    "access_points": "schema_fw",
    "access_points_mview": "schema_fw",
    "c37_118_client_analog_points": "schema_fw",
    "c37_118_client_common_points": "schema_fw",
    "c37_118_client_common_settings": "schema_fw",
    "c37_118_client_digital_points": "schema_fw",
    "c37_118_client_ethernet_settings": "schema_fw",
    "c37_118_client_maps_mview": "schema_fw",
    "c37_118_client_phasor_points": "schema_fw",
    "c37_118_server_analog_points": "schema_fw",
    "c37_118_server_common_points": "schema_fw",
    "c37_118_server_common_settings": "schema_fw",
    "c37_118_server_digital_points": "schema_fw",
    "c37_118_server_ethernet_settings": "schema_fw",
    "c37_118_server_header_settings": "schema_fw",
    "c37_118_server_phasor_points": "schema_fw",
    "c37_118_server_pmu_settings": "schema_fw",
    "c37_118_server_shared_pmu_maps": "schema_fw",
    "c37_118_server_unique_settings": "schema_fw",
    "connections": "schema_fw",
    "courier_client_common_settings": "schema_fw",
    "courier_client_ethernet_settings": "schema_fw",
    "courier_client_trigger_count": "schema_fw",
    "courier_serial_ports": "schema_fw",
    "crc_algorithms": "schema_fw",
    "custom_application_definition_files": "schema_fw",
    "custom_application_definitions": "schema_fw",
    "custom_applications": "schema_fw",
    "datetime_protocol_settings": "schema_fw",
    "datetime_settings": "schema_fw",
    "dnp_client_ai_points": "schema_fw",
    "dnp_client_ao_points": "schema_fw",
    "dnp_client_bi_points": "schema_fw",
    "dnp_client_bo_points": "schema_fw",
    "dnp_client_cnt_points": "schema_fw",
    "dnp_client_common_settings": "schema_fw",
    "dnp_client_custom_request_objects": "schema_fw",
    "dnp_client_custom_requests": "schema_fw",
    "dnp_client_dataset_points": "schema_fw",
    "dnp_client_datasets": "schema_fw",
    "dnp_client_dbi_points": "schema_fw",
    "dnp_client_ethernet_settings": "schema_fw",
    "dnp_client_maps_mview": "schema_fw",
    "dnp_client_unique_settings": "schema_fw",
    "dnp_serial_ports": "schema_fw",
    "dnp_server_ai_points": "schema_fw",
    "dnp_server_ao_points": "schema_fw",
    "dnp_server_authentication_settings": "schema_fw",
    "dnp_server_authentication_user_settings": "schema_fw",
    "dnp_server_bi_points": "schema_fw",
    "dnp_server_bo_points": "schema_fw",
    "dnp_server_cnt_points": "schema_fw",
    "dnp_server_common_settings": "schema_fw",
    "dnp_server_dataset_points": "schema_fw",
    "dnp_server_datasets": "schema_fw",
    "dnp_server_dbi_points": "schema_fw",
    "dnp_server_ethernet_client_settings": "schema_fw",
    "dnp_server_ethernet_settings": "schema_fw",
    "dnp_server_event_and_statistic_points": "schema_fw",
    "dnp_server_maps_mview": "schema_fw",
    "dnp_server_shared_maps": "schema_fw",
    "edna_client_analog_points": "schema_fw",
    "edna_client_common_settings": "schema_fw",
    "edna_client_digital_points": "schema_fw",
    "edna_client_ethernet_settings": "schema_fw",
    "edna_client_maps_mview": "schema_fw",
    "elockout_blocking_tags": "schema_fw",
    "elockout_tag_lists": "schema_fw",
    "ethercat_client_ai_point_settings": "schema_fw",
    "ethercat_client_ai_points": "schema_fw",
    "ethercat_client_ao_point_settings": "schema_fw",
    "ethercat_client_ao_points": "schema_fw",
    "ethercat_client_bi_points": "schema_fw",
    "ethercat_client_bo_points": "schema_fw",
    "ethercat_client_configuration_settings": "schema_fw",
    "ethercat_client_ctpt_points": "schema_fw",
    "ethercat_client_entry_map": "schema_fw",
    "ethercat_client_entry_recording_group_channels": "schema_fw",
    "ethercat_client_entry_settings": "schema_fw",
    "ethercat_client_frequency_groups": "schema_fw",
    "ethercat_client_module_map": "schema_fw",
    "ethercat_client_pdo_settings": "schema_fw",
    "ethercat_client_prctpt_points": "schema_fw",
    "ethercat_client_settings_16ai": "schema_fw",
    "ethercat_client_settings_4aier": "schema_fw",
    "ethercat_client_settings_ctpt": "schema_fw",
    "ethercat_client_settings_prctpt": "schema_fw",
    "ethercat_client_sync_manager_settings": "schema_fw",
    "ethercat_client_voltage_input_points": "schema_fw",
    "ethercat_event_recording_group_channels": "schema_fw",
    "ethercat_index_lookup": "schema_fw",
    "ethercat_map": "schema_fw",
    "ethercat_masters": "schema_fw",
    "ethercat_network_settings": "schema_fw",
    "ethercat_node": "schema_fw",
    "ethercat_node_connections": "schema_fw",
    "expansion_board_contact_input_settings": "schema_fw",
    "flexparse_client_common_settings": "schema_fw",
    "flexparse_client_ethernet_settings": "schema_fw",
    "flexparse_client_flex_parse_messages": "schema_fw",
    "flexparse_client_flex_parse_points": "schema_fw",
    "flexparse_serial_ports": "schema_fw",
    "freeze_counter_request_times": "schema_fw",
    "function_block_bigint": "schema_fw",
    "function_block_boolean": "schema_fw",
    "function_block_inet": "schema_fw",
    "function_block_int": "schema_fw",
    "function_block_master": "schema_fw",
    "function_block_real": "schema_fw",
    "function_block_run_time_settings": "schema_fw",
    "function_block_smallint": "schema_fw",
    "function_block_string": "schema_fw",
    "function_block_struct": "schema_fw",
    "generated_logic_engine_enum_values": "schema_fw",
    "generated_logic_engine_enums": "schema_fw",
    "generated_logic_engine_struct_members": "schema_fw",
    "generated_logic_engine_structs": "schema_fw",
    "generated_logic_engine_tags": "schema_fw",
    "generic_attributes": "schema_fw",
    "goose_rx_config_tag_settings": "schema_fw",
    "goose_rx_rc_settings": "schema_fw",
    "goose_tx_config_tag_settings": "schema_fw",
    "goose_tx_rc_settings": "schema_fw",
    "iec60870_client_101_settings": "schema_fw",
    "iec60870_client_104_settings": "schema_fw",
    "iec60870_client_bit_string_command_points": "schema_fw",
    "iec60870_client_bit_string_points": "schema_fw",
    "iec60870_client_common_settings": "schema_fw",
    "iec60870_client_custom_messages": "schema_fw",
    "iec60870_client_double_command_points": "schema_fw",
    "iec60870_client_double_point_points": "schema_fw",
    "iec60870_client_ethernet_settings": "schema_fw",
    "iec60870_client_integrated_total_points": "schema_fw",
    "iec60870_client_measured_value_points": "schema_fw",
    "iec60870_client_packed_single_point_points": "schema_fw",
    "iec60870_client_points_mview": "schema_fw",
    "iec60870_client_regulating_step_command_points": "schema_fw",
    "iec60870_client_sector_ioa_counts": "schema_fw",
    "iec60870_client_sector_ioas": "schema_fw",
    "iec60870_client_sector_settings": "schema_fw",
    "iec60870_client_setpoint_command_points": "schema_fw",
    "iec60870_client_single_command_points": "schema_fw",
    "iec60870_client_single_point_points": "schema_fw",
    "iec60870_client_step_position_points": "schema_fw",
    "iec60870_serial_ports": "schema_fw",
    "iec60870_server_101_settings": "schema_fw",
    "iec60870_server_104_settings": "schema_fw",
    "iec60870_server_bit_string_command_points": "schema_fw",
    "iec60870_server_bit_string_points": "schema_fw",
    "iec60870_server_common_settings": "schema_fw",
    "iec60870_server_double_command_points": "schema_fw",
    "iec60870_server_double_point_points": "schema_fw",
    "iec60870_server_ethernet_client_settings": "schema_fw",
    "iec60870_server_ethernet_settings": "schema_fw",
    "iec60870_server_integrated_total_points": "schema_fw",
    "iec60870_server_measured_value_points": "schema_fw",
    "iec60870_server_packed_single_point_points": "schema_fw",
    "iec60870_server_regulating_step_command_points": "schema_fw",
    "iec60870_server_sector_ioa_counts": "schema_fw",
    "iec60870_server_sector_ioas": "schema_fw",
    "iec60870_server_sector_settings": "schema_fw",
    "iec60870_server_setpoint_command_points": "schema_fw",
    "iec60870_server_shared_sector_maps": "schema_fw",
    "iec60870_server_single_command_points": "schema_fw",
    "iec60870_server_single_point_points": "schema_fw",
    "iec60870_server_step_position_points": "schema_fw",
    "iec61850_client_3530_settings": "schema_fw",
    "iec61850_client_datasets": "schema_fw",
    "iec61850_client_fcda_tags": "schema_fw",
    "iec61850_client_fcdas": "schema_fw",
    "iec61850_client_poll_groups": "schema_fw",
    "iec61850_client_polled_datasets": "schema_fw",
    "iec61850_client_rc_settings": "schema_fw",
    "iec61850_client_reported_datasets": "schema_fw",
    "iec61850_client_reports": "schema_fw",
    "iec61850_client_tags": "schema_fw",
    "iec61850_server_datasets": "schema_fw",
    "iec61850_server_ethernet_client_settings": "schema_fw",
    "iec61850_server_fcdas": "schema_fw",
    "iec61850_server_logical_devices": "schema_fw",
    "iec61850_server_pou_settings": "schema_fw",
    "iec61850_server_rc_settings": "schema_fw",
    "iec61850_server_report_tags": "schema_fw",
    "iec61850_server_reports": "schema_fw",
    "iec61850_server_shared_map": "schema_fw",
    "iec61850_server_tags": "schema_fw",
    "iec61850_server_unique_settings": "schema_fw",
    "iec_61850_config_file": "schema_fw",
    "last_id_generated": "schema_fw",
    # "lg8979_client_accumulator_points"                  : "schema_fw", EXCLUDE BECAUSE UNUSED
    # "lg8979_client_ai_points"                           : "schema_fw",
    # "lg8979_client_ao_points"                           : "schema_fw",
    # "lg8979_client_ar_points"                           : "schema_fw",
    # "lg8979_client_common_settings"                     : "schema_fw",
    # "lg8979_client_di_points"                           : "schema_fw",
    # "lg8979_client_do_points"                           : "schema_fw",
    # "lg8979_client_ethernet_settings"                   : "schema_fw",
    # "lg8979_client_indication_points"                   : "schema_fw",
    # "lg8979_client_maps_mview"                          : "schema_fw",
    # "lg8979_client_messages"                            : "schema_fw",
    # "lg8979_client_pulse_points"                        : "schema_fw",
    # "lg8979_client_sbo_points"                          : "schema_fw",
    # "lg8979_client_soe_points"                          : "schema_fw",
    # "lg8979_client_unique_settings"                     : "schema_fw",
    # "lg8979_serial_ports"                               : "schema_fw",
    # "lg8979_server_accumulator_points"                  : "schema_fw",
    # "lg8979_server_ai_points"                           : "schema_fw",
    # "lg8979_server_ao_points"                           : "schema_fw",
    # "lg8979_server_ar_points"                           : "schema_fw",
    # "lg8979_server_common_settings"                     : "schema_fw",
    # "lg8979_server_di_points"                           : "schema_fw",
    # "lg8979_server_do_points"                           : "schema_fw",
    # "lg8979_server_ethernet_client_settings"            : "schema_fw",
    # "lg8979_server_ethernet_settings"                   : "schema_fw",
    # "lg8979_server_indication_points"                   : "schema_fw",
    # "lg8979_server_maps_mview"                          : "schema_fw",
    # "lg8979_server_pulse_points"                        : "schema_fw",
    # "lg8979_server_sbo_points"                          : "schema_fw",
    # "lg8979_server_shared_maps"                         : "schema_fw",
    # "lg8979_server_soe_points"                          : "schema_fw",
    # "lg8979_server_unique_settings"                     : "schema_fw",
    # "library_groups"                                    : "schema_fw",
    "live_data_tags": "schema_fw",
    "local_tcp_network_port_connections": "schema_fw",
    "local_tcp_network_ports": "schema_fw",
    "local_udp_network_port_connections": "schema_fw",
    "local_udp_network_ports": "schema_fw",
    "logic_engine_boot_projects": "schema_fw",
    "logic_engine_managed_objects": "schema_fw",
    "logic_engine_ngvl_objects": "schema_fw",
    "logic_engine_pous_collection_objects": "schema_fw",
    "logic_engine_tasks": "schema_fw",
    "logic_engine_user_objects": "schema_fw",
    "logic_engine_user_visualization_manager": "schema_fw",
    "logic_engine_user_visualizations": "schema_fw",
    "main_pou_execution_order": "schema_fw",
    "mainboard_contact_input_settings": "schema_fw",
    "mathmove": "schema_fw",
    "mirrored_bits_maps_mview": "schema_fw",
    "mirrored_bits_settings": "schema_fw",
    "modbus_client_unique_settings": "schema_fw",
    "modbus_coils": "schema_fw",
    "modbus_common_settings": "schema_fw",
    "modbus_discrete_inputs": "schema_fw",
    "modbus_ethernet_settings": "schema_fw",
    "modbus_holding_registers": "schema_fw",
    "modbus_input_registers": "schema_fw",
    "modbus_maps_mview": "schema_fw",
    "modbus_serial_ports": "schema_fw",
    "mot": "schema_fw",
    "ngvl_settings": "schema_fw",
    "password_vault": "schema_fw",
    "pge2179_client_2bit_status_points": "schema_fw",
    "pge2179_client_ai_points": "schema_fw",
    "pge2179_client_calc_points": "schema_fw",
    "pge2179_client_common_settings": "schema_fw",
    "pge2179_client_ethernet_settings": "schema_fw",
    "pge2179_client_maps_mview": "schema_fw",
    "pge2179_client_messages": "schema_fw",
    "pge2179_client_pulse_accum_points": "schema_fw",
    "pge2179_client_sbo_points": "schema_fw",
    "pge2179_client_simple_status_points": "schema_fw",
    "pge2179_client_unique_settings": "schema_fw",
    "pge2179_serial_ports": "schema_fw",
    "read_coil_status_polls": "schema_fw",
    "read_discrete_input_status_polls": "schema_fw",
    "read_holding_register_status_polls": "schema_fw",
    "read_input_register_status_polls": "schema_fw",
    "receive_mirrored_bits": "schema_fw",
    "recording_group_analog_channel_ethercat_settings": "schema_fw",
    "recording_group_channels": "schema_fw",
    "recording_group_channels_mview": "schema_fw",
    "recording_group_custom_channel_points": "schema_fw",
    "recording_group_digital_channel_ethercat_settings": "schema_fw",
    "recording_group_ethercat_clients": "schema_fw",
    "recording_group_num_channels_mview": "schema_fw",
    "recording_group_oscillography_settings": "schema_fw",
    "recording_group_points_mview": "schema_fw",
    "recording_groups": "schema_fw",
    "remote_connections": "schema_fw",
    "remote_device_schema_p_xref": "schema_fw",
    "report_server_id_polls": "schema_fw",
    "sel_client_cascii_labels": "schema_fw",
    "sel_client_check_ied_configuration_commands": "schema_fw",
    "sel_client_common_settings": "schema_fw",
    "sel_client_ethernet_settings": "schema_fw",
    "sel_client_f_read_labels": "schema_fw",
    "sel_client_flex_parse_messages": "schema_fw",
    "sel_client_flex_parse_points": "schema_fw",
    "sel_client_fm_labels": "schema_fw",
    "sel_client_fo_brk_bits": "schema_fw",
    "sel_client_fo_remote_bits": "schema_fw",
    "sel_client_maps_mview": "schema_fw",
    "sel_client_messages": "schema_fw",
    "sel_client_new_event_labels": "schema_fw",
    "sel_client_new_event_messages": "schema_fw",
    "sel_client_rx_uw_messages": "schema_fw",
    "sel_client_rx_uw_registers": "schema_fw",
    "sel_client_ser_points": "schema_fw",
    "sel_client_subprotocols": "schema_fw",
    "sel_client_tx_uw_messages": "schema_fw",
    "sel_client_tx_uw_registers": "schema_fw",
    "sel_server_common_settings": "schema_fw",
    "sel_server_ethernet_settings": "schema_fw",
    "sel_server_maps_mview": "schema_fw",
    "sel_server_passwords": "schema_fw",
    "sel_server_rx_uw_messages": "schema_fw",
    "sel_server_rx_uw_registers": "schema_fw",
    "sel_server_tx_uw_messages": "schema_fw",
    "sel_server_tx_uw_registers": "schema_fw",
    "sel_virtual_ports": "schema_fw",
    "serial_port_connections": "schema_fw",
    "serial_ports": "schema_fw",
    "ses92_client_ai_points": "schema_fw",
    "ses92_client_common_settings": "schema_fw",
    "ses92_client_ethernet_settings": "schema_fw",
    "ses92_client_maps_mview": "schema_fw",
    "ses92_client_messages": "schema_fw",
    "ses92_client_sbo_points": "schema_fw",
    "ses92_client_si_points": "schema_fw",
    "ses92_client_spt_points": "schema_fw",
    "ses92_serial_ports": "schema_fw",
    "ses92_server_accumulator_points": "schema_fw",
    "ses92_server_ai_points": "schema_fw",
    "ses92_server_common_settings": "schema_fw",
    "ses92_server_ethernet_client_settings": "schema_fw",
    "ses92_server_ethernet_settings": "schema_fw",
    "ses92_server_sbo_points": "schema_fw",
    "ses92_server_shared_maps": "schema_fw",
    "ses92_server_spt_points": "schema_fw",
    "ses92_server_ssm_points": "schema_fw",
    "ses92_server_status_points": "schema_fw",
    "ses92_server_unique_settings": "schema_fw",
    "setting_comments": "schema_fw",
    "sftp_server_common_settings": "schema_fw",
    "sftp_server_ethernet_client_settings": "schema_fw",
    "snmp_manager_common_settings": "schema_fw",
    "snmp_manager_control_oids": "schema_fw",
    "snmp_manager_maps_mview": "schema_fw",
    "snmp_manager_polls": "schema_fw",
    "snmp_manager_status_oids": "schema_fw",
    "system_diagnostics": "schema_fw",
    "system_sel_server_ser_points": "schema_fw",
    "tag_constants": "schema_fw",
    "tag_references": "schema_fw",
    "tag_symbol_fb_instance_map": "schema_fw",
    "tag_symbol_map": "schema_fw",
    "tag_task_settings": "schema_fw",
    "tags": "schema_fw",
    "transmit_mirrored_bits": "schema_fw",
    "user_task_list_settings": "schema_fw",
    "user_task_lists": "schema_fw",
    "virtual_tag_lists": "schema_fw",
    "virtual_tag_vt_id": "schema_fw",
    "zzzzzzzzzzzzzzzzzzzz_pg_dump_split_marker": "schema_fw",
}

# Naturally changes between pulls, these are REGEX patterns
RTAC_TRANSIENT_KEYS = [
    ["verified_services"],
    ["users", r".*", "last_access"],
    ["mot", r".*", "project_image"],
    ["last_updated"],
    ["logic_engine_managed_objects", "", "data"],
    ["web_diagnostics", r"Memory Available \(RAM\)"],
    ["web_diagnostics", r"Memory Usage \(RAM\)"],
    ["web_diagnostics", "Storage Usage"],
    ["web_diagnostics", "Power Source Voltage"],
    ["web_diagnostics", "Storage Available"],
    ["web_accounts", "admin"],
    ["device_info", r".*", "users_logged_in"],
    # account used to pull, login date will change,
    # potentially change to verified account dynamically
    ["web_accounts", r".*"],
    # Transients found in RTAC data from a project
    ["round_robin_schemas"],
    ["round_robin_schema_states"],
    ["generic_attributes", r".*", "attr_value"],
]
