from typing import Final

# Source: FortiOS-7.2.9-CLI_Reference.pdf, page 1183
FG_TIMEZONES: Final[dict[int, dict[str, str]]] = {
    1: {"gmt_offset": "-11:00", "timezone": "Midway Island, Samoa"},
    2: {"gmt_offset": "-10:00", "timezone": "Hawaii"},
    3: {"gmt_offset": "-9:00", "timezone": "Alaska"},
    4: {"gmt_offset": "-8:00", "timezone": "Pacific Time (US & Canada)"},
    5: {"gmt_offset": "-7:00", "timezone": "Arizona"},
    6: {"gmt_offset": "-7:00", "timezone": "Mountain Time (US & Canada)"},
    7: {"gmt_offset": "-6:00", "timezone": "Central America"},
    8: {"gmt_offset": "-6:00", "timezone": "Central Time (US & Canada)"},
    9: {"gmt_offset": "-6:00", "timezone": "Mexico City"},
    10: {"gmt_offset": "-6:00", "timezone": "Saskatchewan"},
    11: {"gmt_offset": "-5:00", "timezone": "Bogota, Lima, Quito"},
    12: {"gmt_offset": "-5:00", "timezone": "Eastern Time (US & Canada)"},
    13: {"gmt_offset": "-5:00", "timezone": "Indiana (East)"},
    14: {"gmt_offset": "-4:00", "timezone": "Atlantic Time (Canada)"},
    15: {"gmt_offset": "-4:00", "timezone": "La Paz"},
    16: {"gmt_offset": "-3:00", "timezone": "Santiago"},
    17: {"gmt_offset": "-3:30", "timezone": "Newfoundland"},
    18: {"gmt_offset": "-3:00", "timezone": "Brasilia"},
    19: {"gmt_offset": "-3:00", "timezone": "Buenos Aires"},
    20: {"gmt_offset": "-3:00", "timezone": "Nuuk (Greenland)"},
    21: {"gmt_offset": "-2:00", "timezone": "Mid-Atlantic"},
    22: {"gmt_offset": "-1:00", "timezone": "Azores"},
    23: {"gmt_offset": "-1:00", "timezone": "Cape Verde Is."},
    24: {"gmt_offset": "0:00", "timezone": "Monrovia"},
    25: {
        "gmt_offset": "0:00",
        "timezone": "Dublin, Edinburgh, Lisbon, London, Canary Is.",
    },
    26: {
        "gmt_offset": "+1:00",
        "timezone": "Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    },
    27: {
        "gmt_offset": "+1:00",
        "timezone": "Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    },
    28: {"gmt_offset": "+1:00", "timezone": "Brussels, Copenhagen, Madrid, Paris"},
    29: {"gmt_offset": "+1:00", "timezone": "Sarajevo, Skopje, Warsaw, Zagreb"},
    30: {"gmt_offset": "+1:00", "timezone": "West Central Africa"},
    31: {"gmt_offset": "+2:00", "timezone": "Kyiv, Athens, Sofia, Vilnius"},
    32: {"gmt_offset": "+2:00", "timezone": "Bucharest"},
    33: {"gmt_offset": "+2:00", "timezone": "Cairo"},
    34: {"gmt_offset": "+2:00", "timezone": "Harare, Pretoria"},
    35: {"gmt_offset": "+2:00", "timezone": "Helsinki, Riga, Tallinn"},
    36: {"gmt_offset": "+2:00", "timezone": "Jerusalem"},
    37: {"gmt_offset": "+3:00", "timezone": "Baghdad"},
    38: {"gmt_offset": "+3:00", "timezone": "Kuwait, Riyadh"},
    39: {"gmt_offset": "+3:00", "timezone": "St. Petersburg, Volgograd"},
    40: {"gmt_offset": "+3:00", "timezone": "Nairobi"},
    41: {"gmt_offset": "+3:30", "timezone": "Tehran"},
    42: {"gmt_offset": "+4:00", "timezone": "Abu Dhabi, Muscat"},
    43: {"gmt_offset": "+4:00", "timezone": "Baku"},
    44: {"gmt_offset": "+4:30", "timezone": "Kabul"},
    45: {"gmt_offset": "+5:00", "timezone": "Ekaterinburg"},
    46: {"gmt_offset": "+5:00", "timezone": "Islamabad, Karachi, Tashkent"},
    47: {"gmt_offset": "+5:30", "timezone": "Kolkata, Chennai, Mumbai, New Delhi"},
    48: {"gmt_offset": "+5:45", "timezone": "Kathmandu"},
    49: {"gmt_offset": "+5:00", "timezone": "Almaty, Astana"},
    50: {"gmt_offset": "+6:00", "timezone": "Dhaka"},
    51: {"gmt_offset": "+5:30", "timezone": "Sri Jayawardenepara"},
    52: {"gmt_offset": "+6:30", "timezone": "Rangoon"},
    53: {"gmt_offset": "+7:00", "timezone": "Bangkok, Hanoi, Jakarta, Novosibirsk"},
    54: {"gmt_offset": "+7:00", "timezone": "Krasnoyarsk"},
    55: {
        "gmt_offset": "+8:00",
        "timezone": "Beijing, ChongQing, HongKong, Urumgi, Irkutsk",
    },
    56: {"gmt_offset": "+8:00", "timezone": "Ulaan Bataar"},
    57: {"gmt_offset": "+8:00", "timezone": "Kuala Lumpur, Singapore"},
    58: {"gmt_offset": "+8:00", "timezone": "Perth"},
    59: {"gmt_offset": "+8:00", "timezone": "Taipei"},
    60: {"gmt_offset": "+9:00", "timezone": "Osaka, Sapporo, Tokyo, Seoul"},
    61: {"gmt_offset": "+9:00", "timezone": "Yakutsk"},
    62: {"gmt_offset": "+9:30", "timezone": "Adelaide"},
    63: {"gmt_offset": "+9:30", "timezone": "Darwin"},
    64: {"gmt_offset": "+10:00", "timezone": "Brisbane"},
    65: {"gmt_offset": "+10:00", "timezone": "Canberra, Melbourne, Sydney"},
    66: {"gmt_offset": "+10:00", "timezone": "Guam, Port Moresby"},
    67: {"gmt_offset": "+10:00", "timezone": "Hobart"},
    68: {"gmt_offset": "+10:00", "timezone": "Vladivostok"},
    69: {"gmt_offset": "+10:00", "timezone": "Magadan"},
    70: {"gmt_offset": "+11:00", "timezone": "Solomon Is., New Caledonia"},
    71: {"gmt_offset": "+12:00", "timezone": "Auckland, Wellington"},
    72: {"gmt_offset": "+12:00", "timezone": "Fiji, Kamchatka, Marshall Is."},
    73: {"gmt_offset": "+13:00", "timezone": "Nuku'alofa"},
    74: {"gmt_offset": "-4:00", "timezone": "Caracas"},
    75: {"gmt_offset": "-3:00", "timezone": "Uruguay"},
    76: {"gmt_offset": "+14:00", "timezone": "Kiritimati"},
    77: {"gmt_offset": "-4:00", "timezone": "Georgetown"},
    78: {"gmt_offset": "+1:00", "timezone": "Namibia"},
    79: {"gmt_offset": "0:00", "timezone": "Casablanca"},
    80: {"gmt_offset": "0:00", "timezone": "Greenwich Mean Time"},
    81: {"gmt_offset": "-7:00", "timezone": "Baja California Sur, Chihuahua"},
    82: {"gmt_offset": "+12:45", "timezone": "Chatham Islands"},
    83: {"gmt_offset": "+3:00", "timezone": "Moscow"},
    84: {"gmt_offset": "+3:00", "timezone": "Minsk"},
    85: {"gmt_offset": "+3:00", "timezone": "Istanbul"},
    86: {"gmt_offset": "+13:00", "timezone": "Samoa"},
    87: {"gmt_offset": "-4:00", "timezone": "Paraguay"},
    88: {"gmt_offset": "+12:00", "timezone": "Eniwetok, Kwajalein"},
}
