name: Devcontainer Build

on:
  push:
    branches:
      - main
      - docs/ftp-demo
    paths:
      - pdm.lock
      - pyproject.toml
      - .devcontainer/**
      - .github/workflows/devcontainer.yml
      - .pre-commit-config.yaml
  workflow_dispatch:

jobs:
  docker-build:
    name: Build devcontainer image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0  # checkout full history
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8  # v4.2.0
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c  # v4.2.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0  # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # hack because it's 2026 and github actions still has no native way to make a variable lowercase...
      - name: Lowercase repo
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          subFolder: .github
          imageName: ghcr.io/${{ env.REPO }}/peat-devcontainer
          cacheFrom: ghcr.io/${{ env.REPO }}/peat-devcontainer
          push: always
          platform: linux/amd64,linux/arm64
